name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup Node.js environment for backend
    - name: Setup Node.js for backend
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        working-directory: ./backend

    - name: Install dependencies for backend
      run: npm install
      working-directory: ./backend

    # Run backend tests
    - name: Run backend tests
      run: npm test
      working-directory: ./backend

  frontend-build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup Node.js environment for frontend
    - name: Setup Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        working-directory: ./frontend

    - name: Install dependencies for frontend
      run: npm install
      working-directory: ./frontend

    # Run frontend tests
    - name: Run frontend tests
      run: npm test
      working-directory: ./frontend
